apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: data
resources:
  - namespace.yaml
  - spark-rbac.yaml
  - spark-master.yaml
  - spark-worker.yaml
  - kafka-env-configmap.yaml
